In [1]:
import pandas as pd
import FinanceDataReader as fdr
import matplotlib.pyplot as plt
import matplotlib as mpl

상품선물		<br>
.	NG	천연가스 선물 (NYMEX)<br>
.	ZG	금 선물 (ICE)<br>
.	ZI	은 선물 (ICE)<br>
.	HG	구리 선물 (COMEX)<br>

In [4]:
df_future_gold = fdr.DataReader('ZG', '2000-01-01') # 금 선물 (ICE)
df_future_gold

             Close    Open    High     Low    Volume  Change
Date
2000-01-05   281.1   283.2   283.2   283.2      20.0 -0.0057
2000-01-19   289.8   289.8   289.8   289.8      20.0  0.0042
2000-01-28   283.0   287.1   287.8   280.5   14490.0 -0.0143
2000-01-31   283.2   283.0   284.5   282.1    2450.0  0.0007
2000-02-01   282.5   282.3   284.0   282.2     500.0 -0.0025
...            ...     ...     ...     ...       ...     ...
2020-12-30  1893.4  1881.8  1899.0  1879.5  133660.0  0.0056
2020-12-31  1895.1  1899.0  1904.9  1889.1  130630.0  0.0009
2021-01-04  1946.6  1908.2  1948.7  1906.1  273370.0  0.0237
2021-01-05  1954.4  1946.0  1957.0  1938.4  201950.0  0.0040
2021-01-06  1908.6  1952.8  1962.5  1902.6  366610.0 -0.0234

[4112 rows x 6 columns]